// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using final_413.Models;

namespace final_413.Migrations
{
    [DbContext(typeof(QuoteContext))]
    partial class QuoteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24");

            modelBuilder.Entity("final_413.Models.Quote", b =>
                {
                    b.Property<int>("QuoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Citation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Quote_body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.HasKey("QuoteId");

                    b.ToTable("Quotes");

                    b.HasData(
                        new
                        {
                            QuoteId = 1,
                            Author = "Will Ferrell",
                            Quote_body = "Before you marry a person, you should first make them use a computer with slow Internet to see who they really are."
                        },
                        new
                        {
                            QuoteId = 2,
                            Author = "Will Durant",
                            Date = "1926",
                            Quote_body = "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
                            Subject = "Philosophy"
                        },
                        new
                        {
                            QuoteId = 3,
                            Author = "Harvey Specter",
                            Date = "2015",
                            Quote_body = "It’s not bragging if it’s true."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
